### ISSUE TITLE
Combine on an Array

### ISSUE THREAD

**Issue by ymer** [greenflash1357/Digits.jl#5]
Could the combine function be extended to also work on arrays?

Like so:
`combine([1,2,3,4])`
`1234`

**Comment by ymer** [comment]
A suggested implementation on https://github.com/ymer/Digits

**Comment by greenflash1357** [comment]
The function you are looking for might be `undigit` combined with `reverse!` because of the order of digits that is imposed by Julias `digits` function.

```
julia> undigit(reverse!([1,2,3,4]))
1234
```

**Comment by ymer** [comment]
Ah, you're right! It doesn't look very clear in the code though.
